# Project information
site_name: 'Webtechnologie 1'
site_description: 'Onderwijsmateriaal voor de module Webtechnologie HBO-ICT jaar 1 semester 2'
site_url: 'https://misja.github.io/webtech1/'
use_directory_urls: false

# Repository
repo_url: 'https://github.com/misja/webtech1'
repo_name: 'misja/webtech1'
edit_uri: 'edit/main/docs/'

theme:
  name: 'material'
  language: 'nl'
  icon:
    logo: 'material/library'
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: 'blue grey'
      accent: 'orange'
      toggle:
        icon: material/brightness-7
        name: Schakel naar donkere modus
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: 'blue grey'
      accent: 'orange'
      toggle:
        icon: material/brightness-4
        name: Schakel naar lichte modus
  features:
    # Navigation
    - navigation.instant        # Snelle navigatie zonder page reload
    - navigation.instant.prefetch  # Prefetch pages on hover
    - navigation.tracking       # URL updates met active anchor
    - navigation.top            # Back-to-top button
    - navigation.path           # Breadcrumb navigatie
    - navigation.indexes        # Section index pages
    # Search
    - search.suggest            # Search suggestions
    - search.highlight          # Highlight search terms
    # Content
    - content.code.copy         # Copy button bij code blocks
    - content.code.annotate     # Code annotations
    - content.action.edit       # "Edit this page" knop
    - content.action.view       # "View source" knop

markdown_extensions:
  # Python Markdown extensions
  - abbr                        # Abbreviations met tooltips
  - admonition                  # Admonition blocks
  - attr_list                   # HTML attributes op Markdown elementen (nodig voor images, buttons, etc.)
  - def_list                    # Definition lists
  - footnotes                   # Footnotes
  - md_in_html                  # Markdown in HTML blocks
  - tables                      # Tables
  - toc:                        # Table of contents
      permalink: true
      permalink_title: Link naar deze sectie
      toc_depth: 3
  # PyMdown Extensions
  - pymdownx.arithmatex:        # Math formulas
      generic: true
  - pymdownx.betterem:          # Verbeterde emphasis
      smart_enable: all
  - pymdownx.caret              # Superscript en insert
  - pymdownx.critic             # Track changes
  - pymdownx.details            # Collapsible admonitions
  - pymdownx.emoji:             # Emoji support
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:         # Code highlighting (vervangt codehilite)
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite       # Inline code highlighting
  - pymdownx.keys               # Keyboard keys
  - pymdownx.magiclink          # Auto-link URLs
  - pymdownx.mark               # Highlight text
  - pymdownx.smartsymbols       # Smart symbols
  - pymdownx.superfences        # Code blocks (vervangt fenced_code)
  - pymdownx.tabbed:            # Content tabs
      alternate_style: true
  - pymdownx.tasklist:          # Task lists
      custom_checkbox: true
  - pymdownx.tilde              # Subscript en delete

plugins:
  - search:                     # Search plugin met Nederlandse config
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])'
      lang: nl
  - glightbox                   # Image zoom/lightbox (vervangt custom modal JS/CSS)

# Copyright en extra links
copyright: |
  &copy; 2024 Hanzehogeschool Groningen -
  <a href="https://github.com/misja/webtech1/issues/new" target="_blank">Meld een probleem of onduidelijkheid</a>

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/misja/webtech1
      name: GitHub Repository
    - icon: fontawesome/solid/bug
      link: https://github.com/misja/webtech1/issues
      name: Meld een probleem

nav:
  - Start: index.md
  - Week 1 - HTML/CSS/Bootstrap:
    - HTML:
      - week1/1.html/html-deel1.md
      - week1/1.html/html-deel2.md
      - week1/1.html/html-deel3.md
      - week1/1.html/html-deel4.md
    - CSS:
      - week1/2.css/css-deel1.md
      - week1/2.css/css-deel2.md
      - week1/2.css/css-deel3.md
    - Bootstrap:
      - week1/3.bootstrap/bootstrap-deel1.md
      - week1/3.bootstrap/bootstrap-deel2.md
      - week1/3.bootstrap/bootstrap-deel3.md
      - week1/3.bootstrap/bootstrap-deel4.md
    - Oefeningen:
      - week1/oefeningen/wk1oefening1.md
      - week1/oefeningen/wk1oefening2.md
      - week1/oefeningen/wk1oefening3.md
      - week1/oefeningen/wk1oefening4.md
      - week1/oefeningen/wk1oefening5.md
  - Week 2 - OOP:
    - week2/oop-deel1.md
    - week2/oop-deel2.md
    - week2/oop-deel3.md
    - week2/oop-deel4.md
    - Oefeningen:
      - week2/oefeningen/oop-oefening1.md
      - week2/oefeningen/oop-oefening2.md
      - week2/oefeningen/oop-oefening3.md
      - week2/oefeningen/oop-oefening4.md
  - Week 3 - SQLite:
    - week3/sql-deel1.md
    - week3/python-exceptions.md
    - week3/sql-deel2.md
    - week3/sql-deel3.md
    - week3/sql-deel4.md
    - week3/sql-deel5.md
    - week3/sql-deel6.md
    - Oefeningen:
      - week3/oefeningen/sql-oefening1.md
      - week3/oefeningen/sql-oefening2.md
      - week3/oefeningen/sql-oefening3.md
      - week3/oefeningen/sql-oefening4.md
  - Week 4 - Flask:
    - week4/flask-deel1.md
    - week4/flask-deel2.md
    - week4/flask-deel3.md
    - week4/flask-deel4.md
    - Oefeningen:
      - week4/oefeningen/flask-oefening1.md
  - Week 5 - Flask Forms:
    - week5/flask-forms-deel1.md
    - week5/flask-forms-deel2.md
    - week5/flask-forms-deel3.md
    - Oefeningen:
      - week5/oefeningen/flask-forms-oefening1.md
  - Week 6 - Flask Views:
    - week6/flask-views-deel1.md
    - week6/flask-views-deel2.md
    - week6/flask-views-deel3.md
    - week6/flask-views-deel4.md
    - week6/flask-views-deel5.md
    - Oefeningen:
      - week6/oefeningen/flask-views-oefening1.md
  - Week 7a - User Authentication:
    - week7a/user-authentication-deel1.md
    - week7a/user-authentication-deel2.md
    - week7a/user-authentication-deel3.md
    - week7a/user-authentication-deel4.md
  - Week 7b - Flask Applicaties:
    - week7b/flask-applicaties-deel1.md
    - week7b/flask-applicaties-deel2.md
    - week7b/flask-applicaties-deel3.md
  - Projecten:
    - projecten/index.md
    - projecten/bungalowpark.md
    - projecten/filmfan.md
    - projecten/programmeerles.md
    - projecten/stage.md
